### ISSUE TITLE
可以加个参数,调用本地开发 server 时可以使用 http 吗?

### ISSUE THREAD

**Issue by robgu** [hjkcai/wepy-plugin-axios#1]
Requesting an http URL is not allowed

**Comment by hjkcai** [comment]
更新到0.1.7版本就行了，在`NODE_ENV`不是`production`的时候都不会强制要求https了

**Comment by robgu** [comment]
验证过了,可行的.谢谢

**Comment by jingxinxin** [comment]
更新到0.1.7版本了，在NODE_ENV不是production的时候 也会强制要求https
npm run dev 
NODE_ENV是undefined



let baseURL = 'https://www.xxxxxx.com'
if (__DEV__) baseURL = 'http://localhost:3000'

const request = axios.create({
  adapter: adapter,      // 此属性为可以在小程序中使用 axios 的关键
  // ...其它属性
  baseURL,
  timeout: 1000
})

**Comment by hjkcai** [comment]
@jingxinxin 看一下编译后的 `wepy-plugin-axios/lib/adapter.js` 文件里面的相关代码，然后修改一下这个文件吧，可能是 wepy 更新后更改了 `NODE_ENV` 判断机制
