### ISSUE TITLE
yarn workspaces的兼容问题？

### ISSUE THREAD

**Issue by Fnxxxxo** [hjkcai/wepy-plugin-axios#4]
Readme里说不能共用node_modules，那就是yarn workspaces所有同级的wepy项目都会被这个改动影响？

**Comment by hjkcai** [comment]
试一下吧…其实我不太清楚= = 

目前这个项目是针对很旧的 wepy 版本设计的了，那个时候必须通过 plugin 修改 axios 的代码才行。现在通过配置可能不需要了，但我目前没有时间研究，抱歉哈
