### ISSUE TITLE
adapter如何调用？

### ISSUE THREAD

**Issue by jansonjoan** [hjkcai/wepy-plugin-axios#6]
在哪个位置调用adapter呢？怎么调用？求解

**Comment by hjkcai** [comment]
不用调用adapter啊，把adapter传进`axios.create`里面去就是了

**Comment by jansonjoan** [comment]
axios.create写在哪里的？

**Comment by hjkcai** [comment]
写在一个公共模块里面，然后其它的模块去调用这个模块

类似这样
https://github.com/hjkcai/cardiovascular-tracker/blob/master/client/src/lib/axios.js

**Comment by jansonjoan** [comment]
好的，明白了

**Comment by superlbr** [comment]
@hjkcai 是不是每次instance请求前都要setToken？

**Comment by superlbr** [comment]
嗯，不需要， [axios global setting](https://github.com/axios/axios#global-axios-defaults)
