### ISSUE TITLE
库适用范围

### ISSUE THREAD

**Issue by shenqihui** [hjkcai/wepy-plugin-axios#8]
看了下 readme 以及 adapter 的部分代码，感觉这个适用于所有的小程序，而并非只适用于 wepy 。

adapter 里面的请求都是适用 wx 对象下面的请求，回调也是适用 success 和 fail 进行操作的。

所以我觉得，可以把名字非 wepy-plugin 。

另外，我打算在我新的小程序框架下面适用这个插件了。

感谢这个 axios 配置。

**Comment by hjkcai** [comment]
是的，这个东西完全可以放到其它小程序框架里面用。其实限定在 wepy 里面也是有历史原因的，当初做这个库的时候市面上只有 wepy 一个小程序框架，而且需要依靠框架把 axios 中的 Node.js 部分去除，否则框架会尝试把 fs, http 这些模块打包进去。主要是当时不想 fork axios，想找个简单点的实现方式😂

前段时间我也有考虑把这个库通用化，但看到 axios 正在策划 1.0 版，而且是大改，所以我想等到 axios 出 1.0 了再做一波移植。

觉得好用点个赞吧哈哈
