### ISSUE TITLE
是不是不支持axios.all

### ISSUE THREAD

**Issue by luotingv1** [hjkcai/wepy-plugin-axios#9]
是不是不支持axios.all  在wepy里面用这个apl报错

**Comment by hjkcai** [comment]
必须支持，发一下具体的代码和报错信息

**Comment by luotingv1** [comment]
![image](https://user-images.githubusercontent.com/24503005/43310921-8ed67048-91bb-11e8-8009-631ea4da6862.png)
![image](https://user-images.githubusercontent.com/24503005/43310933-9aebbba4-91bb-11e8-9d86-3112c433f908.png)
上面是错误编译信息

![image](https://user-images.githubusercontent.com/24503005/43310959-a99fe396-91bb-11e8-8133-3dbf579d661a.png)
这是正常的请求 不会报错  axios.all 就报错

**Comment by hjkcai** [comment]
只有直接引入的 axios 才有 `axios.all` 方法。你这里的 `axios` 一定是 `axios.create` 后返回的对象吧，所以会报错。

其实解决方法很简单，直接把 `axios.all` 换成 `Promise.all` 就行。根据 axios 的源码(https://github.com/axios/axios/blob/master/lib/axios.js#L45 )，`axios.all` 就是 `Promise.all`：

```javascript
axios.all = function all(promises) {
  return Promise.all(promises);
};
```

**Comment by luotingv1** [comment]
![image](https://user-images.githubusercontent.com/24503005/43374542-c9dba00e-93e2-11e8-9e5a-736e2b6e02b1.png)
![image](https://user-images.githubusercontent.com/24503005/43374550-d4ff5a52-93e2-11e8-864d-c987577100d5.png)
还是不行啊  会报错

**Comment by hjkcai** [comment]
你用错了，Promise.all 的参数是数组，不能直接那样写

**Comment by luotingv1** [comment]
谢谢 已经搞定
